// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfygbMex4XSYhwJmycnNaC_luUFFHHp4',
    appId: '1:422931650774:web:74988f98eade8ccc25d177',
    messagingSenderId: '422931650774',
    projectId: 'apna--tiffin',
    authDomain: 'apna--tiffin.firebaseapp.com',
    storageBucket: 'apna--tiffin.firebasestorage.app',
    measurementId: 'G-9NSFBGVJRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdS-f4VGcY3Kbnswk_U5dzrQAbNDbAII',
    appId: '1:422931650774:android:177e1003c389219025d177',
    messagingSenderId: '422931650774',
    projectId: 'apna--tiffin',
    storageBucket: 'apna--tiffin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp6Vb9xwggJ206zN83qyatbKtOwvp-gkc',
    appId: '1:422931650774:ios:4ca176783cec1e3c25d177',
    messagingSenderId: '422931650774',
    projectId: 'apna--tiffin',
    storageBucket: 'apna--tiffin.firebasestorage.app',
    iosBundleId: 'com.example.apnaTiffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp6Vb9xwggJ206zN83qyatbKtOwvp-gkc',
    appId: '1:422931650774:ios:4ca176783cec1e3c25d177',
    messagingSenderId: '422931650774',
    projectId: 'apna--tiffin',
    storageBucket: 'apna--tiffin.firebasestorage.app',
    iosBundleId: 'com.example.apnaTiffin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfygbMex4XSYhwJmycnNaC_luUFFHHp4',
    appId: '1:422931650774:web:d6837d537700ab8c25d177',
    messagingSenderId: '422931650774',
    projectId: 'apna--tiffin',
    authDomain: 'apna--tiffin.firebaseapp.com',
    storageBucket: 'apna--tiffin.firebasestorage.app',
    measurementId: 'G-2WF25NX10P',
  );
}
